[package]
name = "simple_blog"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
tower = { version = "0.5.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
uuid = {version = "1.17.0", features = ["v4", "serde"]}
reqwest = { version = "0.12.15", features = ["json"] }
chrono = { version = "0.4.41", features = ["serde", "clock"] }

axum = "0.8.4"
serde_json = "1.0"
anyhow = "1.0.98"
jsonwebtoken = "9.3.1"

